spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:23306/blog_api
    username: user
    password: qwer
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        type: trace
        show_sql: true
        format_sql: true
        use_sql_comments: false
        default_batch_fetch_size: 1000
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

server:
  port: 80
#
#---
#
#spring:
#  profiles:
#    active: prod
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://quick-maria:3306/blog_api
#    username: user
#    password: qwer
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        type: trace
#        show_sql: true
#        format_sql: true
#        use_sql_comments: false
#        default_batch_fetch_size: 1000
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#      use-new-id-generator-mappings: false
#  thymeleaf:
#    prefix : classpath:templates/
#    suffix : .html
#    cache : false
#
#server:
#  port: 80